//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSActiveProduct
    {
        public int ActiveProductsID { get; set; }
        public int LocationsID { get; set; }
        public int MasterCatID { get; set; }
        public int SubCatID { get; set; }
        public string Brand { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    }
}
