//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSLocation
    {
        public int LocationsID { get; set; }
        public string LocationsName { get; set; }
        public int RecPeriod { get; set; }
        public int MarketID { get; set; }
        public string SpecialPricing { get; set; }
        public string Address { get; set; }
        public string CityStateZip { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string QBCustomerName { get; set; }
        public string SavedReconcile { get; set; }
        public Nullable<int> RollUpPeriod { get; set; }
        public Nullable<decimal> RME60 { get; set; }
        public Nullable<decimal> DISTRO60 { get; set; }
        public Nullable<decimal> DISTRO100 { get; set; }
        public Nullable<decimal> DISTRO120 { get; set; }
        public Nullable<decimal> RMEsalts { get; set; }
        public Nullable<decimal> DISTROsalts { get; set; }
        public Nullable<decimal> CBD { get; set; }
        public Nullable<decimal> Kratom { get; set; }
        public Nullable<decimal> Accessories { get; set; }
        public Nullable<decimal> Hardware { get; set; }
        public Nullable<decimal> PrefilledPods { get; set; }
        public Nullable<decimal> fourtwenty { get; set; }
    }
}
