//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSReconcileClose
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LocationsId { get; set; }
        public string LocationsName { get; set; }
        public Nullable<int> RecPeriod { get; set; }
        public string SavedReconcile { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
