//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSReconcile
    {
        public int ReconcileID { get; set; }
        public int LocationsID { get; set; }
        public int RecPeriod { get; set; }
        public System.DateTime RecDate { get; set; }
        public string AddDeductOnly { get; set; }
        public int ProductID { get; set; }
        public int WalkInCount { get; set; }
        public int NumSold { get; set; }
        public int NumAdd { get; set; }
        public int NumDeduct { get; set; }
        public int WalkOutCount { get; set; }
    }
}
