//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSRollup
    {
        public int RollUpID { get; set; }
        public int MarketID { get; set; }
        public int LocationsID { get; set; }
        public int ProductID { get; set; }
        public string DMYA { get; set; }
        public Nullable<System.DateTime> RUDate { get; set; }
        public Nullable<int> RUMonth { get; set; }
        public string RUYear { get; set; }
        public Nullable<int> MasterCatID { get; set; }
        public int SubCatID { get; set; }
        public Nullable<decimal> StockValue { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<int> NumAdd { get; set; }
        public Nullable<int> NumSold { get; set; }
    }
}
