//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSpecialPricing
    {
        public int SpecialPricingID { get; set; }
        public int LocationsID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal Consignment { get; set; }
    }
}
