//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWYWmember
    {
        public int MemberID { get; set; }
        public string CellNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string email { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string Zip { get; set; }
        public string ZipPlus5 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
