//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWYWshop
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string BMorONLINE { get; set; }
        public string ShopType { get; set; }
        public string ShopGender { get; set; }
        public string GiftCard { get; set; }
        public string GiftCardImageName { get; set; }
    }
}
