//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWYWwishitem
    {
        public int WishItemID { get; set; }
        public int WishListID { get; set; }
        public string ItemType { get; set; }
        public int ShopID { get; set; }
        public string ShopName { get; set; }
    }
}
