//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LocationsId { get; set; }
        public string AddDeductOnly { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceFilePath { get; set; }
        public string ReportFIlePath { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
