//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuiceStation
    {
        public int Recordid { get; set; }
        public string JuiceName { get; set; }
        public string JuiceDescription { get; set; }
        public string Vendor { get; set; }
        public string Lenexa { get; set; }
    }
}
