//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCcustomer
    {
        public int CustomerID { get; set; }
        public int AssociateID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string FedTaxIdNumber { get; set; }
        public string Active { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> VaporRoomJoinDate { get; set; }
        public string VaporGroup { get; set; }
        public System.DateTime LastActivity { get; set; }
        public string PaypalEmail { get; set; }
        public string RetailOrAssociate { get; set; }
        public System.DateTime BirthDate { get; set; }
    }
}
