//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCJuice
    {
        public int ProductID { get; set; }
        public Nullable<int> SubID { get; set; }
        public int Size { get; set; }
        public int NIC { get; set; }
        public int StockCount { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
