//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCSale
    {
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int CustomerID { get; set; }
        public int AssociateID { get; set; }
        public Nullable<int> UplineAssociateID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Shipping { get; set; }
        public decimal Total { get; set; }
        public string PaymentType { get; set; }
        public string AssocStock { get; set; }
        public System.DateTime ShipDate { get; set; }
        public decimal AssocCom { get; set; }
        public Nullable<decimal> UplineAssocCom { get; set; }
        public Nullable<decimal> CompanyCom { get; set; }
        public bool OrderComplete { get; set; }
        public string Paypal_InvoiceID { get; set; }
    }
}
