//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCTempOrder
    {
        public int entryid { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> shiptotal { get; set; }
        public Nullable<decimal> taxtotal { get; set; }
        public Nullable<decimal> invtotal { get; set; }
        public Nullable<decimal> discounttotal { get; set; }
        public Nullable<System.DateTime> ordercompleteddate { get; set; }
        public string remarks { get; set; }
        public Nullable<int> status { get; set; }
    }
}
