//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCTempOrderDetail
    {
        public int entryid { get; set; }
        public Nullable<int> temp_oid { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> ProductSubID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<decimal> tax { get; set; }
    }
}
