//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVAccountProdVideo_bk
    {
        public int VSVAccountID { get; set; }
        public int AccountVidID { get; set; }
        public int VidID { get; set; }
        public string URL { get; set; }
        public string Shown { get; set; }
        public Nullable<int> VSVLocationID { get; set; }
    }
}
