//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVAccount
    {
        public int VSVAccountID { get; set; }
        public string AcctName { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SamplesAddress1 { get; set; }
        public string SamplesAddress2 { get; set; }
        public string SamplesCity { get; set; }
        public string SamplesState { get; set; }
        public string SamplesZip { get; set; }
        public string DMPhone { get; set; }
        public string DMName { get; set; }
        public string DMEmail { get; set; }
        public Nullable<short> SamplesNICLevel { get; set; }
        public Nullable<short> GMT { get; set; }
        public string MonStart { get; set; }
        public string MonStop { get; set; }
        public string TueStart { get; set; }
        public string TueStop { get; set; }
        public string WedStart { get; set; }
        public string WedStop { get; set; }
        public string ThurStart { get; set; }
        public string ThurStop { get; set; }
        public string FriStart { get; set; }
        public string FriStop { get; set; }
        public string SatStart { get; set; }
        public string SatStop { get; set; }
        public string SunStart { get; set; }
        public string SunStop { get; set; }
    }
}
