//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVEntertainmentVideo1
    {
        public int EVID { get; set; }
        public int MGID { get; set; }
        public int MusicID { get; set; }
        public int ArtistID { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
