//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVLocation
    {
        public int VSVAccountID { get; set; }
        public int VSVLocationID { get; set; }
        public string LocationName { get; set; }
        public string YouTubeChannel { get; set; }
        public Nullable<int> ShuffleRatio { get; set; }
        public Nullable<int> ShuffleRatioProduct { get; set; }
    }
}
