//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVManufacturer
    {
        public int ManID { get; set; }
        public string ManName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SampleEmail { get; set; }
        public string PromoEmail { get; set; }
    }
}
