//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVPromo
    {
        public int PromosID { get; set; }
        public int ManID { get; set; }
        public System.DateTime PromoStart { get; set; }
        public int BrandID { get; set; }
        public string BottleSize { get; set; }
        public string TheOffer { get; set; }
        public System.DateTime PromoEnd { get; set; }
        public string TargetNew { get; set; }
        public string TargetExisting { get; set; }
        public Nullable<int> VidID { get; set; }
    }
}
