//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVPromoRequestSummary
    {
        public int PromoRequestSummaryID { get; set; }
        public int ManID { get; set; }
        public int BrandID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int PromoRequestCount { get; set; }
        public Nullable<System.DateTime> dateSummary { get; set; }
    }
}
