//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVShopIntro
    {
        public int ShopIntroID { get; set; }
        public int VSVAccountID { get; set; }
        public string IntroURL { get; set; }
        public Nullable<int> VSVLocationID { get; set; }
    }
}
