//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVSampleLog
    {
        public int LogID { get; set; }
        public int ManID { get; set; }
        public int BrandID { get; set; }
        public int VidID { get; set; }
        public System.DateTime DateStamp { get; set; }
        public int VSVAccountID { get; set; }
    }
}
