//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser_HTML_File_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSVuserVid_09dec2020
    {
        public int UserVidID { get; set; }
        public int VSVUserID { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public string Shown { get; set; }
        public Nullable<int> EVID { get; set; }
    }
}
